Changed Image positions and dimensions and added border to image
IIITM-Jay/Property-management-System-Django-Full-Stack- pull request #24
Opened 2021-01-06 10:51 UTC by 96RadhikaJadhav

Changed Image positions and dimensions and added border to image in flow_sequence_diag.md

This PR will resolve issue #11 .

2021-01-06 13:26 UTC, IIITM-Jay requested changes
no border is visible ....
Try to fix it, if you are facing any problem then feel free to share it here

2021-01-06 13:26 UTC, IIITM-Jay commented on DBMS module/flow_sequence_diag.md
> +<img width="650" height="700" src="/images/flow-sequensce.png" alt="Flow sequence diagram" border= "7" style= "display: block; margin-left: auto; margin-right: auto; ">
@96RadhikaJadhav I think the border is not yet set....
Is the border visible to you,... 
if yes, then can you attach the screenshot here.

2021-01-06 14:46 UTC, IIITM-Jay commented
@96RadhikaJadhav Thanks for the first PR... :1st_place_medal: :tada: :champagne: :sparkles:
There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. :+1:

2021-01-06 14:51 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav Thanks for the first PR... 🥇 🎉 🍾 ✨
> There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. 👍

@IIITM-Jay  While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?

2021-01-06 14:53 UTC, IIITM-Jay commented
@96RadhikaJadhav I have open up one discussion #25 , go through it deliver your ideas there and also encourage your friends, juniors and colleagues also to join this repo and team.. :+1:

2021-01-06 14:54 UTC, IIITM-Jay commented
> > @96RadhikaJadhav Thanks for the first PR... 1st_place_medal tada champagne sparkles
> > There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. +1
> 
> @IIITM-Jay While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?

I will look tomorrow regarding this...

2021-01-06 14:55 UTC, 96RadhikaJadhav commented
> > > @96RadhikaJadhav Thanks for the first PR... 1st_place_medal tada champagne sparkles
> > > There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. +1
> > 
> > 
> > @IIITM-Jay While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?
> 
> I will look tomorrow regarding this...

Sure :) .

2021-01-06 15:16 UTC, 96RadhikaJadhav commented
> > > > @96RadhikaJadhav Thanks for the first PR... 1st_place_medal tada champagne sparkles
> > > > There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. +1
> > > 
> > > 
> > > @IIITM-Jay While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?
> > 
> > 
> > I will look tomorrow regarding this...
> 
> Sure :) .

![image](https://user-images.githubusercontent.com/56536997/103782296-497c5e00-505d-11eb-842f-82a4f8abb050.png)

2021-01-06 15:19 UTC, 96RadhikaJadhav commented
> > > > > @96RadhikaJadhav Thanks for the first PR... 1st_place_medal tada champagne sparkles
> > > > > There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. +1
> > > > 
> > > > 
> > > > @IIITM-Jay While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?
> > > 
> > > 
> > > I will look tomorrow regarding this...
> > 
> > 
> > Sure :) .
> 
> ![image](https://user-images.githubusercontent.com/56536997/103782296-497c5e00-505d-11eb-842f-82a4f8abb050.png)

![image](https://user-images.githubusercontent.com/56536997/103784949-9dd50d00-5060-11eb-9d97-b1fd079d148d.png)
 And this one is for atom editor showing border

2021-01-08 07:13 UTC, 96RadhikaJadhav commented
> > > > > > @96RadhikaJadhav Thanks for the first PR... 1st_place_medal tada champagne sparkles
> > > > > > There is no hurry , you can complete this as your own conviniency level and sure we can fix those and this is the platform where you can open your thoughts. +1
> > > > > 
> > > > > 
> > > > > @IIITM-Jay While making changes I have opened file in atom editor and the border was visible there. But now when I tried opening the file through chrome, the image isn't visible to me so can't see if the border is there or not? Any suggestions how can I fix this issue?
> > > > 
> > > > 
> > > > I will look tomorrow regarding this...
> > > 
> > > 
> > > Sure :) .
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56536997/103782296-497c5e00-505d-11eb-842f-82a4f8abb050.png)
> 
> ![image](https://user-images.githubusercontent.com/56536997/103784949-9dd50d00-5060-11eb-9d97-b1fd079d148d.png)
> And this one is for atom editor showing border

Hi @IIITM-Jay   Did you get any time to check on this?

2021-01-08 07:14 UTC, 96RadhikaJadhav commented
> Hi @IIITM-Jay Did you get any time to check on this?

Meanwhile I have tried using different markdown extension in chrome. But here it's still not showing image but the border is visible.

![image](https://user-images.githubusercontent.com/56536997/103985620-472a1900-51af-11eb-943f-053b6c6116ef.png)

2021-01-08 07:32 UTC, 96RadhikaJadhav commented
> > Hi @IIITM-Jay Did you get any time to check on this?
 
The image along with border is now visible. Please see below image.

![image](https://user-images.githubusercontent.com/56536997/103986953-abe67300-51b1-11eb-848d-7a71b68d6df5.png)

Please share your thoughts on this and let me know if it's good to be merged, so that I can take up another issue in this project :) .

2021-01-08 11:39 UTC, IIITM-Jay commented
@96RadhikaJadhav I must think that you have'nt updated the PR and perhaphs you have made changes to your local repo that you have cloned in your PC :worried: :disappointed: :confused: 

One more important thing I would like to share with you that as far as, there is a continuous flow of the conversation there is no need to quote the reply again and again, as it would be then difficult (must guess you also foud it ugly and difficult) for searching the exact new thing that you are sharing, by saying this I would like to say that quote the reply when there is a misunderstanding of the communication or any flaw occur in the consistency and whenever you feel necessary.

2021-01-08 12:34 UTC, IIITM-Jay commented
@96RadhikaJadhav Radhika , I would suggest you to please push the updated file with border specifications once again ....

2021-01-08 17:20 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav I must think that you have'nt updated the PR and perhaphs you have made changes to your local repo that you have cloned in your PC 😟 😞 😕
> 
> One more important thing I would like to share with you that as far as, there is a continuous flow of the conversation there is no need to quote the reply again and again, as it would be then difficult (must guess you also found it ugly and difficult) for searching the exact new thing that you are sharing, by saying this I would like to say that quote the reply when there is a misunderstanding of the communication or any flaw occur in the consistency and whenever you feel necessary.

Yeah sorry for that! I noticed that after replying to messages 😞. Will take care of it further.

2021-01-08 17:33 UTC, 96RadhikaJadhav commented
@IIITM-Jay  There is a lot of confusion for me now 😞. While pushing I'm getting error like Error: failed to push some refs. I did some searching and tried to pushed it again but its still not getting pushed 😟.
If you allow can I create a fresh PR including all image dimensions and position details along with border.

2021-01-09 14:03 UTC, IIITM-Jay commented
@96RadhikaJadhav I would suggest you to go through once here :point_down: 
[github-git error:failed](https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to-remote)

2021-01-10 05:21 UTC, 96RadhikaJadhav commented
@IIITM-Jay  I have already gone through the same link that you've provided. But still getting error. If you don't mind can you please provide your mail id, need your assistance on the issue.

2021-01-12 18:24 UTC, 96RadhikaJadhav commented
> @IIITM-Jay I have already gone through the same link that you've provided. But still getting error. If you don't mind can you please provide your mail id, need your assistance on the issue.

@IIITM-Jay  Meanwhile I have tried all other ways regarding the issue I'm facing. But it's not getting committed. If you are busy, can we just ignore this PR and will create a new one. 
If not, please provide your mail id, we can discuss the issue there.

2021-01-13 11:44 UTC, IIITM-Jay commented
@96RadhikaJadhav I think you havn't tried by editing the previous PR and then push it online without the use CLI... I think it should work.
**Steps:**
1. Go to the online repository at github.
2. Open up your PR there.
3. Go to the file you have pushed in the repective PR.
4. At the right corner you will find *edit the file* button
5. Click on it and then do the necessary changes and then it will ask you for the push button.

After doing this, let me know if you are not able to do it or facing any such difficulties.
Actually I am on the journey that's why it's taking a lot of time to reply... kindly ignore those :bowing_man:

2021-01-13 17:15 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav I think you havn't tried by editing the previous PR and then push it online without the use CLI... I think it should work.
> **Steps:**
> 
> 1. Go to the online repository at github.
> 2. Open up your PR there.
> 3. Go to the file you have pushed in the repective PR.
> 4. At the right corner you will find _edit the file_ button
> 5. Click on it and then do the necessary changes and then it will ask you for the push button.
> 
> After doing this, let me know if you are not able to do it or facing any such difficulties.
> Actually I am on the journey that's why it's taking a lot of time to reply... kindly ignore those 🙇‍♂️

@IIITM-Jay  That was super easy. Thank you :) . I committed changes. Please see if the border is visible to you now. Also please let me know if any other changes required.

2021-01-16 10:54 UTC, IIITM-Jay commented
@96RadhikaJadhav I think now also not visible... see once :disappointed:

2021-01-16 10:57 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav I think now also not visible... see once 😞

Ohh no..But it is visible to me both in editor as well as chrome. Not sure why it's not visible to you 😞.

2021-01-16 10:58 UTC, 96RadhikaJadhav commented
@IIITM-Jay Leave it then 😞..Don't merge the PR.

2021-01-16 11:02 UTC, 96RadhikaJadhav commented
@IIITM-Jay  So can I work on other issues in this repository??

2021-01-16 12:22 UTC, IIITM-Jay commented
@96RadhikaJadhav why you are giving up in so much hurry. you can explore more on flavored markdown and css/ html that's the only solution to this issue. It's not too late.

Are you a part of any winter of code, or preparing for any other platforms? :thinking:

2021-01-16 14:03 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav why you are giving up in so much hurry. you can explore more on flavored markdown and css/ html that's the only solution to this issue. It's not too late.
> 
> Are you a part of any winter of code, or preparing for any other platforms? 🤔

No, I'm not part of any of such programs. Sure, I will do more research on it and will get back to you.

2021-01-18 15:38 UTC, 96RadhikaJadhav commented
![image](https://user-images.githubusercontent.com/56536997/104935176-e8e01000-59d0-11eb-97cd-c3951cd4c7ba.png)


@IIITM-Jay  As per the new changes, the border is as seen in above screenshot.  Please let me know if the changes are now visible to you or not.

2021-01-20 10:55 UTC, IIITM-Jay commented
@96RadhikaJadhav for me it's showing grey boundary only and not the black as you posted the screenshot.
You can view your file too that you pushed at the right corner you will find the option to view the file.

Because I must guess that you are viewing with your local repo and it's showing perfectly there but when you will view on the online repo it's not .

Just check it by yourself and let me know

2021-01-21 05:04 UTC, IIITM-Jay commented on DBMS module/flow_sequence_diag.md
> +<kbd><img width="650" height="700" src="../images/flow-sequensce.png" alt="Flow sequence diagram" style="border: 4px solid black" style= "display: block; margin-left: auto; margin-right: auto; "></kb
@96RadhikaJadhav May I know the significance of using ```<kbd>``` here :thinking:

2021-01-21 05:05 UTC, IIITM-Jay reviewed
![Screenshot from 2021-01-21 10-43-38](https://user-images.githubusercontent.com/65283880/105282515-8b1c1580-5bd4-11eb-9ce2-0e163582aed4.png)
I have left one query @96RadhikaJadhav , let me know .... and also attaching the screenshot os what is visible based on your changes

2021-01-21 08:20 UTC, 96RadhikaJadhav commented on DBMS module/flow_sequence_diag.md
> +<kbd><img width="650" height="700" src="../images/flow-sequensce.png" alt="Flow sequence diagram" style="border: 4px solid black" style= "display: block; margin-left: auto; margin-right: auto; "></kb
When I searched it on stack overflow, in one of the answers I found this tag. So tried applying it.

2021-01-21 09:15 UTC, 96RadhikaJadhav commented
@IIITM-Jay  I have tried several commits and viewed that file in online repo. It's same. Tried removing <kbd> tag, but then, no border is visible. I guess one more way to resolve the issue is I can remove the existing image file and can add new image file with the border added to it. Please let me know your thoughts on this.
Or else if you say, I will do more research and will try to come up with some new changes to make border visible.

2021-01-25 10:11 UTC, IIITM-Jay commented
@96RadhikaJadhav Radhika if you wish and want to try the above method, feel free to try and see the effect ... 🍾

2021-02-07 16:13 UTC, IIITM-Jay commented
@96RadhikaJadhav Sorry :disappointed:  Radhika for letting you wait for so long... its ready to get merged... although the image you uploaded with black boundary is visible as gray but still I appreciate :1st_place_medal: your harwork and efforts :champagne: Congratulations for being a part of this repository. Thank you so much... :tada: :sparkles: :sparkler: :100:

2021-02-07 16:15 UTC, merged

2021-02-21 12:01 UTC, IIITM-Jay commented
@all-contributors please add @96RadhikaJadhav for documentation

2021-02-21 12:03 UTC, IIITM-Jay commented
@all-contributors please add @96RadhikaJadhav for design

2021-02-21 12:28 UTC, IIITM-Jay commented
@all-contributors please add @96RadhikaJadhav for design