updated the image caption #14
IIITM-Jay/Property-management-System-Django-Full-Stack- pull request #34
Opened 2021-01-23 11:54 UTC by Amit366

Added the image caption.

2021-01-23 15:40 UTC, Amit366 commented
@iiitmjay I have updated it.

2021-01-25 10:19 UTC, IIITM-Jay commented on README.md
> +<figcaption>Road Map for Property Management System</figcaption>
Amit @Amit366 the caption is not in the middle...
Can you try bringing it to the middle

2021-01-25 10:19 UTC, IIITM-Jay requested changes
@Amit366 try to bring it to the center of the page

2021-01-25 10:46 UTC, IIITM-Jay commented
Amit @Amit366 if all the files have similar modification ... No need to push the same again and again

2021-01-25 10:51 UTC, IIITM-Jay commented
Amit @Amit366 no need to push the same file for nearly 10 times, it will not look professional...
If something went wrong ask the mentor/ maintainer of the project repo for clarification

2021-01-25 10:53 UTC, Amit366 commented
And when I am trying to center it, it is moving to the right.

2021-01-25 11:03 UTC, IIITM-Jay commented
> Sorry sir. Actually the Vscode stopped working thats why I am implementing the changes in the github itself.

No need to say sorry and try to learn and understand things... As the reviewers may also not find difficulties while reviewing..🤗

2021-01-25 11:06 UTC, Amit366 commented
> And when I am trying to center it, it is moving to the right.

Sir can you help me?

2021-01-25 13:31 UTC, closed without merging