table centered
IIITM-Jay/Property-management-System-Django-Full-Stack- pull request #36
Opened 2021-01-27 18:46 UTC by himanshu007-creator

2021-01-30 01:05 UTC, IIITM-Jay commented on README.md
> +
@himanshu007-creator Himanshu, this is simply an HTML code, can you try using the markdown format as it is the standard format for writing the readme files.

2021-01-30 01:06 UTC, IIITM-Jay requested changes
Himanshu @himanshu007-creator try  using markdown as well as flavored markdown

2021-01-30 02:07 UTC, himanshu007-creator commented
> Himanshu @himanshu007-creator try using markdown as well as flavored markdown

Okay sir, will try it today

2021-01-30 05:26 UTC, himanshu007-creator commented
i am working on it sir, but i don't think there is a way to align a table created in markdown in center.

2021-01-31 13:40 UTC, himanshu007-creator commented
sir, i dont think there is a way to center align a table created in markdown. I have checked many discussions on many platforms, but all proved useless. So HTML table is the only solution.

2021-02-07 15:59 UTC, IIITM-Jay commented
@himanshu007-creator Himanshu okay , so go ahead with updating the PR with a new file as the last page contains some errors...

2021-02-07 16:01 UTC, himanshu007-creator commented
> @himanshu007-creator Himanshu okay , so go ahead with updating the PR with a new file as the last page contains some errors...

I have corrected them. Please check

2021-02-07 16:24 UTC, IIITM-Jay commented
@himanshu007-creator Himanshu once again see by adding a new file. Do one thing do not make any changes, upload the unchanged file (with the same file that is already present in this repo without any changes done by you) from your side again and will get merged soon.

2021-02-07 16:26 UTC, IIITM-Jay commented
Soory himanshu @himanshu007-creator but I have been asked to label it as level 1 that's why I changed it to that..

2021-02-07 16:28 UTC, himanshu007-creator commented
> @himanshu007-creator Himanshu once again see by adding a new file. Do one thing do not make any changes, upload the unchanged file (with the same file that is already present in this repo without any changes done by you) from your side again and will get merged soon.

done sir

2021-02-07 16:34 UTC, IIITM-Jay commented
Himanshu @himanshu007-creator If you want this to be labeled as level 3 or 4, can you create two bages namely frontend view and backend view that will link to the same. The link I will provide you late but first can you try building up badges as the one you are seeing at the top of the **Readme.md** file.

2021-02-07 16:36 UTC, himanshu007-creator commented
> Himanshu @himanshu007-creator If you want this to be labeled as level 3 or 4, can you create two badges namely frontend view and backend view that will link to the same. The link I will provide you later , so don't worry about the links but first can you try building up badges as the one you are seeing at the top of the **Readme.md** file and show me the designed badges.

Yes, I can make them sir

2021-02-07 16:40 UTC, himanshu007-creator commented
> Himanshu @himanshu007-creator If you want this to be labeled as level 3 or 4, can you create two badges namely frontend view and backend view that will link to the same. The link I will provide you later , so don't worry about the links but first can you try building up badges as the one you are seeing at the top of the **Readme.md** file and show me the designed badges.

please have a look now 😃

2021-02-15 10:27 UTC, IIITM-Jay commented
@himanshu007-creator Himanshu look it once again the file you have changed ... you have not yet cleared unwanted...

2021-02-15 10:28 UTC, himanshu007-creator commented
> @himanshu007-creator Himanshu look it once again the file you have changed ... you have not yet cleared unwanted...

sir, can you tell which lines exactly?

2021-02-15 10:29 UTC, himanshu007-creator commented
> Himanshu @himanshu007-creator If you want this to be labeled as level 3 or 4, can you create two badges namely frontend view and backend view that will link to the same. The link I will provide you later , so don't worry about the links but first can you try building up badges as the one you are seeing at the top of the **Readme.md** file and show me the designed badges.

did this too, so i think now labels should be made <code> level-3</code> or <code> level-4</code>

2021-02-15 10:36 UTC, IIITM-Jay commented
@himanshu007-creator sorry to say Himanshu but this can go as level 2 when I asked and cleared the same in detail... I found so

2021-02-15 10:37 UTC, IIITM-Jay commented
@himanshu007-creator Himanshu is it okay with you...

2021-02-15 10:38 UTC, IIITM-Jay commented
@Nandini-Jha I think this can be merged now :hugs:

2021-02-15 10:38 UTC, himanshu007-creator commented
> @himanshu007-creator Himanshu is it okay with you...

totally fine!

2021-02-15 10:40 UTC, IIITM-Jay commented
@himanshu007-creator Great work Himanshu... :tada: :sparkles: 
Thank you so much for your contributions.
Once gain welcoming you and cogratulating to be a part of the Property Management System :house_with_garden:

2021-02-15 10:40 UTC, merged

2021-02-15 10:41 UTC, himanshu007-creator commented
> @himanshu007-creator Great work Himanshu... 🎉 ✨
> Thank you so much for your contributions.
> Once gain welcoming you and cogratulating to be a part of the Property Management System 🏡

welcome sir!

2021-02-21 11:37 UTC, IIITM-Jay commented
@all-contributors please add @himanshu007-creator  for content